### PR TITLE
NXP-23936: add back Audit Storage module and package

### PR DESCRIPTION
**Pull request by funshodavid**

### CODE REVIEW

**Comment by pgmillon** [comment]
Hi, this should rather be done in a 1.0_9.10 branch

**Comment by funshodavid** [comment]
Closing this pull request to release this package through a new `1.0_9.10` branch.

**Comment by pgmillon** [comment]
👍

**Comment by pgmillon** [comment]
Please update/make PR on https://github.com/nuxeo/integration-scripts/blob/9.10/marketplace.ini :)

**Comment by efge** [comment]
👍

**Comment by egiuly-nuxeo** [comment]
👍

**Pull request merged**
